#!/bin/bash

# API Testing Commands
# API runs on http://localhost:8080

echo "=========================================="
echo "API TESTING COMMANDS"
echo "=========================================="
echo ""

echo "1. START THE API SERVER:"
echo "   cd /Users/miksan/Desktop/rp"
echo "   python3 api/app.py"
echo ""
echo "   (Keep this terminal open - server runs in foreground)"
echo ""

echo "2. TEST HEALTH ENDPOINT (in a new terminal):"
echo "   curl http://localhost:8080/health"
echo ""

echo "3. TEST SINGLE PREDICTION:"
echo "   curl -X POST http://localhost:8080/predict \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{"
echo "       \"breed\": \"Chihuahua\","
echo "       \"age\": 6,"
echo "       \"weight\": 2.8,"
echo "       \"medical_history\": \"None\","
echo "       \"genetic_predispositions\": \"None\","
echo "       \"current_medications\": \"None\","
echo "       \"diet\": \"Balanced\","
echo "       \"lifestyle\": \"Indoor\","
echo "       \"environment\": \"Temperate\","
echo "       \"vaccination_status\": \"Not Up-to-date\","
echo "       \"neutering_status\": \"Neutered\","
echo "       \"living_conditions\": \"Multi-pet\","
echo "       \"disease\": \"Hypersensitivity Allergic Dermatosis\","
echo "       \"stage\": \"Severe\""
echo "     }'"
echo ""

echo "4. TEST WITH PYTHON SCRIPT:"
echo "   python3 api/test_api.py"
echo ""

echo "5. TEST WITH ENHANCED FEATURES:"
echo "   curl -X POST http://localhost:8080/predict \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{"
echo "       \"breed\": \"Labrador\","
echo "       \"age\": 5,"
echo "       \"weight\": 25.0,"
echo "       \"medical_history\": \"None\","
echo "       \"genetic_predispositions\": \"None\","
echo "       \"current_medications\": \"None\","
echo "       \"diet\": \"Grain-free\","
echo "       \"lifestyle\": \"Active\","
echo "       \"environment\": \"Temperate\","
echo "       \"vaccination_status\": \"Up-to-date\","
echo "       \"neutering_status\": \"Neutered\","
echo "       \"living_conditions\": \"Single-pet\","
echo "       \"disease\": \"Fungal Infections\","
echo "       \"stage\": \"Initial\","
echo "       \"severity_score\": 45,"
echo "       \"symptom_count\": 3,"
echo "       \"previous_treatment\": \"None\","
echo "       \"previous_treatment_response\": \"None\","
echo "       \"treatments_tried_count\": 0,"
echo "       \"drug_allergies\": \"None\","
echo "       \"drug_interaction_risk\": \"Low\","
echo "       \"cost_category\": \"Affordable\","
echo "       \"availability_status\": \"In Stock\""
echo "     }'"
echo ""

echo "=========================================="

